version: '3.8'

services:
  client:
    build: ./client/
    ports:
      - '3000:3000'
    environment:
      BACKEND_HOST: 'localhost:8080'

  server:
    build: ./server/
    ports:
      - '8080:8080'
    volumes:
      - storage:/data

volumes:
  storage:
