version: '3.8'

services:
  client:
    build: ./client/
    ports:
      - '3000:3000'
    environment:
      BACKEND_HOST: 'localhost:8080'

  server:
    build: ./server/
    ports:
      - '8080:8080'
    environment:
      REDIS_PASSWORD: bobflix
    volumes:
      - storage:/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    environment: 
      REDIS_PASSWORD: bobflix

volumes:
  storage:
